### ISSUE TITLE
Use Delimiters and Consistent Classifiers in Entity Names in file broad-dsp-techops-dev.yml

### ISSUE THREAD

**Issue by rmeffan** [broadinstitute/dsp-ansible-configs#4]
Suggestions for file `broad-dsp-techops-dev.yml` are inline in the code block.

```
- hosts: dockerol2 (Don't run name components together; use a separator. Example: docker-ol2)
  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: "{{ item }}"
    with_items:
      - ansible-role-basepackages
      - ansible-role-docker

- hosts: dockerlvm (Don't run name components together; use a separator. Example: docker-lvm)
  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: "{{ item }}"
    with_items:
      - ansible-role-basepackages
      - ansible-role-docker
      - ansible-docker-provision-thinpool (Your other names have ansible-role- as a prefix. How is this item different? Feels like there should be a classifier between ansible and docker.)
```
