### ISSUE TITLE
Use Consistent Entity Names in file provisioner.yaml

### ISSUE THREAD

**Issue by rmeffan** [broadinstitute/dsp-ansible-configs#5]
Suggestions for file `provisioner.yaml` are inline in the code block.

```
---
- hosts: localhost
  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: ansible-pull-configure (If this is a role, it should be ansible-role-pull-configure to follow the naming pattern used for other roles.)
    vars:
      branch: master
```
